[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "22"

[[redirects]]
  from = "/players"
  to = "/ranking"
  status = 301

[[redirects]]
  from = "/index.html"
  to = "/"
  status = 301
